---
- name: Descargar y descomprimir 
  unarchive:
    src: "{{ URL }}"
    dest: "{{ home }}"
    remote_src: yes    
    
- name: Mover el binario
  shell: mv "{{ home }}/linux-amd64/helm" /usr/local/bin/helm  