---
- name: Crea carpeta .kube en $HOME
  file:
    path: /home/vagrant/.kube         
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant
  listen: contexto

- name: Copiar archivos de configuración
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: true
    mode: 0755
    owner: vagrant
    group: vagrant
  listen: contexto  

    
    
    
    
       

